### ISSUE TITLE
Command print out should copy and pastable.

### ISSUE THREAD

**Issue by zglozman** [ngs-lang/ngs#106] opened 2018-07-30 16:48 UTC
when ngs prints out the args of a failed external command they should  not be seprated by commas, and i should be able to cut and pase it with ease

**Comment by ilyash-b** [comment] 2018-08-01 04:49
Quoting is also needs to be implemented (for spaces and special characters). For that we probably need `encode_bash` method.

**Comment by ilyash-b** [comment] 2019-03-26 20:49
Duplicate of #203

**Closed by ilyash-b** 2019-03-26 20:49 UTC
Labels: aspect/UI, correctness, enhancement
