### ISSUE TITLE
NGS Shouid stop failing on start 

### ISSUE THREAD

**Issue by zglozman** [ngs-lang/ngs#86] opened 2018-07-28 14:18 UTC
zglozman@dardas1:~/MuleProject/Ubinet/lambdas/gs-lamba-api$ ngs
*** NGS CLI is under construction ***
| After successful command, R variable contains the result
| After unsuccessful command, E variable contains the exception
[ERROR 2018-07-28 10:17:34 EDT] --- Exception ---
[ERROR 2018-07-28 10:17:34 EDT] Exception of type DlopenFail occurred
[ERROR 2018-07-28 10:17:34 EDT] Message: Failed to dlopen()
[ERROR 2018-07-28 10:17:34 EDT] Info: filename = String(16): libreadline.so.6
[ERROR 2018-07-28 10:17:34 EDT] Frame 0: /usr/local/lib/ngs/bootstrap.ngs:294:1 - 294:34
[ERROR 2018-07-28 10:17:34 EDT] Frame 1: /usr/local/lib/ngs/bootstrap.ngs:267:20 - 267:29 [in bootstrap_exception_catch_wrapper]
[ERROR 2018-07-28 10:17:34 EDT] Frame 2: /usr/local/lib/ngs/bootstrap.ngs:201:11 - 201:23 [in bootstrap]
[ERROR 2018-07-28 10:17:34 EDT] Frame 3: /usr/local/lib/ngs/cli.ngs:98:1 - 98:4
[ERROR 2018-07-28 10:17:34 EDT] Frame 4: /usr/local/lib/ngs/cli.ngs:41:7 - 41:10 [in cli]
[ERROR 2018-07-28 10:17:34 EDT] Frame 5: /usr/local/lib/ngs/autoload/FFI.ngs:25:11 - 25:15 [in init]
[ERROR 2018-07-28 10:17:34 EDT] Frame 6: /usr/local/lib/ngs/autoload/FFI.ngs:11:36 - 11:44 [in CLib]

**Comment by ilyash-b** [comment] 2018-07-28 14:21
Duplicate of #21

**Closed by ilyash-b** 2018-07-28 14:21 UTC
Labels: bug, correctness, must-have
